name: Deploy dotfiles
on:
    push:
        branches: 
          - main
          - macos-config
    workflow_dispatch:
jobs:
    deploy:
        runs-on: macos-15
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: Run setup script with deploy CI flag
          run: |
            chmod +x setup.sh
            ./setup.sh --configure-macos
        
        - name: Wait for GUI applications to start
          run: sleep 10
        
        - name: Take desktop screenshot
          run: |
            screencapture -x ~/Desktop/dotfiles-setup-result.png
            ls -la ~/Desktop/dotfiles-setup-result.png
        
        - name: Upload screenshot as artifact
          uses: actions/upload-artifact@v4
          with:
            name: dotfiles-screenshot
            path: ~/Desktop/dotfiles-setup-result.png
            retention-days: 30