name: Deploy dotfiles
on:
    push:
        branches:
        - main
    workflow_dispatch:
jobs:
    deploy:
        runs-on: macos-15
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        
        - name: CI setup run
          run: |
            chmod +x setup.sh
            ./setup.sh --deploy-ci